In [1]:
import pandas as pd

# Load your full CSV (make sure it's in the same folder)
df = pd.read_csv("E-COMMERCE.csv")

# Take a smaller sample (20,000 rows)
df_small = df.sample(20000, random_state=42)

# Save it as a new CSV
df_small.to_csv("E-COMMERCE_SMALL.csv", index=False)

print("Smaller CSV created successfully!")

Smaller CSV created successfully!

In [2]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [3]:
df_small = df.sample(20000, random_state=42)

In [4]:
df_small

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
209268,555200,71459,HANGING JAM JAR T-LIGHT HOLDER,24,2011-06-01 12:05:00,0.85,17315.0,United Kingdom
207108,554974,21128,GOLD FISHING GNOME,4,2011-05-27 17:14:00,6.95,14031.0,United Kingdom
167085,550972,21086,SET/6 RED SPOTTY PAPER CUPS,4,2011-04-21 17:05:00,0.65,14031.0,United Kingdom
471836,576652,22812,PACK 3 BOXES CHRISTMAS PANETTONE,3,2011-11-16 10:39:00,1.95,17198.0,United Kingdom
115865,546157,22180,RETROSPOT LAMP,2,2011-03-10 08:40:00,9.95,13502.0,United Kingdom
...,...,...,...,...,...,...,...,...
157156,550193,22094,RED RETROSPOT TISSUE BOX,12,2011-04-15 09:27:00,1.25,13952.0,United Kingdom
64923,541682,22077,6 RIBBONS RUSTIC CHARM,12,2011-01-20 15:00:00,1.65,14770.0,United Kingdom
419704,572854,22726,ALARM CLOCK BAKELIKE GREEN,10,2011-10-26 12:28:00,3.39,14096.0,United Kingdom
500580,578789,23103,JINGLE BELL HEART DECORATION,24,2011-11-25 12:17:00,1.65,16161.0,United Kingdom
92453,544191,82484,WOOD BLACK BOARD ANT WHITE FINISH,6,2011-02-16 16:57:00,7.95,13089.0,United Kingdom